### ISSUE TITLE
URI encoding of email address type user

### ISSUE THREAD

**Issue by danielparas** [millercl/gulp-webdav-sync#3]
Hi, first of all thanks for this package!

I'm having trouble connecting to a WebDAV server that uses an email address as the username. Seems like a URI encode is being done on `options.auth` as the connection string with `options.auth` set to `daniel@example.com:password` is generated as follows in the console log:

```
https://daniel%40example.com:password@server-name.com/dav/
```

Which causes the server to return access denied 403

Any ideas of how to make this work?

Thanks in advance!
Daniel

**Comment by danielparas** [comment]
Apologies for this please ignore this post

**Comment by millercl** [comment]
The URI encoding behaviour is [`url.format`](https://nodejs.org/api/url.html#url_url_format_urlobj) ( not explicit as of [v1.0.0](https://github.com/millercl/gulp-webdav-sync/releases/tag/v1.0.0) ). [Virtuoso OpenSource](https://github.com/openlink/virtuoso-opensource) may return `403` for a permission error, _e.g._ non-admin user `PUT` in `/DAV/`, but will return `401` for a non-existent user.
