### ISSUE TITLE
Doesn't handle relative paths correctly.

### ISSUE THREAD

**Issue by MobiusHorizons** [millercl/gulp-webdav-sync#4]
Because base_dir is always resolved to an absolute path, but vinyl_path is not always resolved to an absolute path, I am getting the error 'Incoherent Target: paths diverge.' This can be fixed i believe by replacing _splice_target_stem with 
    
    path.relative(base_dir, path.resolve(vinyl_path))

**Comment by millercl** [comment]
Please provide the call, complete error message, output with options = {
'log':'log' } set, and a directory listing.

**Comment by MobiusHorizons** [comment]
This is probably an artifact of my gulp workflow, but in [`_splice_target_stem`](https://github.com/millercl/gulp-webdav-sync/blob/master/index.js#L601)  `vinyl_path` is an absolute path, for example `/Users/..../base_dir/somepath/`) where `base_dir` is `/Users/.../base_dir`

Because you are doing pure string operations on mixed relative/ absolute paths, this function does not work.

Using the code listed above should work in all cases. Although you may need to do a check for `"../.*"` in the output string to make sure it errors on directories not inside of `base_dir`

**Comment by millercl** [comment]
Can you see paths in the error message? Sorry, try like this

```js
var webdav = require( 'gulp-webdav-sync' )

gulp.task( 'test', function () {
  var href = 'http://localhost/'
  var options = {
    'log': 'log'
    , 'base': '/etc'
  }
  var transform = webdav( href, options )
  transform.on( 'error', function ( e ) { // catch
    console.log( 'error: ' + e ) 
  } )
  console.log( 'cwd: ' + process.cwd() ) // check
  return gulp.src( 'file' )
    .pipe( transform )
}

gulp.task( 'test-watch', function () {
  var href = 'http://localhost/'
  var options = {
    'log': 'log'
    , 'base': '/etc' 
  }
  console.log( 'cwd: ' + process.cwd() )
  gulp.watch( 'file', [ 'test' ] )
    .on( 'change', dav( href, options ).watch )
} )
```
`_splice_target_stem` does assume its arguments are absolute paths. 
if `_splice_target_stem` is provided with invalid arguments, such as a relative path, then it may return an invalid value. 
gulp-webdav-sync assumes path resolution relative to the current working directory, i.e. `process.cwd()`. 
`_splice_target_stem` expects objects created by `gulp.src` and `gulp.watch` calls.

`_splice_target_stem` is called directly, and as a subroutine in `_splice_target`.
`_splice_target` does not make any assignments to `base_dir` before providing it as a parameter `_splice_target_stem`, i.e. read-only.
`_splice_target` does not make any assignments to `vinyl_path` before providing it as a parameter to `_splice_target_stem`, i.e. read-only.
if `_splice_target_stem` receives invalid arguments from `_splice_target`, then `_splice_target` is provided with invalid arguments.
all calls to `_splice_target` and _splice_target_stem wrap the base_dir parameter as `path.resolve( _options.base )`.
[`path.resolve`](https://nodejs.org/api/path.html#path_path_resolve_from_to) returns an absolute path.
Therefore ( as you say ) `base_dir` should always be an absolute path.
`gulp.task` ( [`stream._tranform`](https://github.com/millercl/gulp-webdav-sync/blob/84efa607077b253c212f63734d29a8ab752a721e/index.js#L116) ) calls to `_splice_target` and `_splice_target_stem` provide a [vinyl File.path](https://github.com/gulpjs/vinyl#optionspath) ( vinyl.path ) .
https://github.com/gulpjs/vinyl#optionspath is a "full path", i.e. an absolute path.
if the vinyl's File.path is not an absolute path, then the value is inconsistent with documentation.
if the vinyl's File.path value is inconsistent with documentation, then the issue should be filed with fractal's project.
`gulp.watch` ( [`stream._watch`](https://github.com/millercl/gulp-webdav-sync/blob/84efa607077b253c212f63734d29a8ab752a721e/index.js#L244) ) calls to `_splice_target` and `_splice_target_stem` provide a [globwatcher change event](https://github.com/gulpjs/glob-watcher/blob/dbea1bff005bb9cc4bdf888f3f91058931d5bfeb/index.js#L10).
[globwatcher documentation](https://github.com/gulpjs/glob-watcher/blob/6611454fd9c1827af4b8e84f4bb7299e0e01d46c/README.md) does not detail the change event ( as a relative or absolute path ).
if globwatcher event paths are sometimes relative and sometimes absolute, then the values are inconsistent.
if globwatcher event path values are inconsistent, then the issue should be filed with gulpjs's project.

`vinyl_path` and `base_dir` should both be absolute paths.
"/Users/..../base_dir/somepath/" and "/Users/.../base_dir" are absolute paths.

**Comment by millercl** [comment]
`path.resolve` is similar in function but not an adequate replacement as you give.

**Comment by millercl** [comment]
If passing absolute and relative path globs and any absolute glob is not under `base_dir`, then either `Incoherent Target: options.base too long.` or `Incoherent Target: paths diverge.` will be emitted (depending on which path has a longer string length).
```js
gulp.task( 'test', function () {
  var transform = webdav( href, options )
    transform.on( 'error', function ( e ) {
      console.log( e )
    } )
  return gulp.src( [  'js/*.js', '/tmp/misc' ] )
    .pipe( transform )
}
```

**Comment by millercl** [comment]
gulp-webdav-sync v1.0.0 does not handle `/` as a `base_dir` properly.

**Comment by millercl** [comment]
@MobiusHorizons Thanks for your suggestion, aa99c1d0cb33bbfd60fb4c92b32583b46052d11f. Please try [v1.0.1](https://github.com/millercl/gulp-webdav-sync/releases/tag/v1.0.1) available on [npm](https://www.npmjs.com/package/gulp-webdav-sync).

**Comment by MobiusHorizons** [comment]
@millercl I have chosen to use https://github.com/bermi/webdav-sync for the time being. (not grunt, but works well) If i have a chance, i will report progress here.
