### ISSUE TITLE
gulp crashes, when file on source machine exists, but on destination side it does not 

### ISSUE THREAD

**Issue by konstantinast** [millercl/gulp-webdav-sync#6]
Sometimes source machine has a file and the destination machine (webdav supporting server) does not have it.

Because of this the following happens: response.propstat[0].prop[0].getlastmodified property becomes typeof undefined (a.k.a simply does not exists) and this causes the infamous JS error "TypeError: Cannot read property '0' of undefined", which in turn crashes gulp task, which looks something like this:

```
    var webdav = require( 'gulp-webdav-sync' );    

    gulp.task( 'overwrite-destination-content', function () {
        var local_source_path = 'target_directory';
        var target_path = local_source_path + '/**/*';

        var options = {
            auth: 'username:password',
            hostname: 'www.example.com',
            log: 'info',
            logAuth: true,
            base: local_source_path
        };

        gulp.src(target_path)
            .pipe(webdav( options ))
        ;
    }); 
```

Just wanted to share this info. Sadly as I've needed this fix asap (setting up env for my project co-workers and this was a blocker), I've forked your repository, made a small adjustment to your index.js file (can be seen in here https://github.com/konstantinast/gulp-webdav-sync/pull/1 ) and even setup a temporary (I hope) npm library for our project to use :)

**Comment by millercl** [comment]
Please try with
```js
var options = {
  // etc.
  uselastmodified: false,
}
```
to force uploading as a workaround.

https://github.com/millercl/gulp-webdav-sync#optionsuselastmodified

If you have the response content (XML), that would be helpful to see.

**Comment by millercl** [comment]
[v1.0.3](https://github.com/millercl/gulp-webdav-sync/releases/tag/v1.0.3) should correct this.
Places sample XML files in [`multistatus`](https://github.com/millercl/gulp-webdav-sync/commit/47af021a8b056e668811d5ddf8af14f76feae21e#diff-b5b6c54705d763265811975053e7a15c) if you are still having trouble.
